#define FRAME_WIDTH		2.9f
#define BOT_FRAME_WIDTH	8.0f

#define SCREEN_WIDTH	21.0f
#define H_SCREEN_WIDTH	(SCREEN_WIDTH / 2)
#define SCREEN_HEIGHT	15.75f
#define H_SCREEN_HEIGHT	(SCREEN_HEIGHT / 2)

#define BART_WIDTH	(SCREEN_WIDTH + 2 * FRAME_WIDTH)
#define BART_HEIGHT	(SCREEN_HEIGHT + 2 * FRAME_WIDTH)

#define GERTJAN_WIDTH	(SCREEN_WIDTH + 2 * FRAME_WIDTH)
#define GERTJAN_HEIGHT	(SCREEN_WIDTH + 2 * FRAME_WIDTH)
#define GERTJAN_OFFSET	(GERTJAN_HEIGHT / 2 - FRAME_WIDTH - H_SCREEN_HEIGHT)

#define MARTIJN_WIDTH	(SCREEN_HEIGHT + 2 * FRAME_WIDTH)
#define MARTIJN_HEIGHT	(SCREEN_WIDTH + 2 * FRAME_WIDTH)

#define BOX_WIDTH		BART_WIDTH
#define H_BOX_WIDTH		(BOX_WIDTH / 2)

#define BOX_HEIGHT		GERTJAN_HEIGHT
#define H_BOX_HEIGHT	(BOX_HEIGHT / 2)

#define BOX_DEPTH		MARTIJN_WIDTH
#define H_BOX_DEPTH		(BOX_DEPTH / 2)